### PR TITLE
Add --no-examples option

### PR DESCRIPTION
**Pull request by karlhorky**
Closes microsoft/playwright#29896

cc @mxschmitt

### CODE REVIEW

**Review by mxschmitt — APPROVED** [review]

**Comment by karlhorky** [comment]
@mxschmitt thanks for the review and merge!

**Comment by karlhorky** [comment]
@mxschmitt thanks for the review and merge!

I assume that this will be included in [`create-playwright@1.18.0`](https://github.com/microsoft/create-playwright/releases/tag/v1.18.0)? Or will this go out in a patch release with [`create-playwright@1.17.132`](https://github.com/microsoft/create-playwright/releases/tag/v1.17.132)?

**Comment by karlhorky** [comment]
@mxschmitt friendly ping - is it possible to get a new version published with this change?

**Comment by karlhorky** [comment]
@mxschmitt Nice, thanks for the publish of [`create-playwright@1.17.133`](https://github.com/microsoft/create-playwright/releases/tag/v1.17.133) 🙌

**Pull request merged**
