### PR TITLE
feat: detect bun package manager

### PR DESCRIPTION
**Pull request by colinhacks**
This makes it so `create-playwright` detects when its run with `bunx` and uses Bun for package management and script execution.

### CODE REVIEW

**Comment by colinhacks** [comment]
Bun doesn't have a native Windows build so it'll be tricky to get CI working till that happens. I'm marking this as a draft until then.

**Comment by karlhorky** [comment]
getting close! almost 95% now as of 20 Mar 2024

- https://twitter.com/bunjavascript/status/1770298099833151867

**Comment by karlhorky** [comment]
Bun 1.1 supports Windows!

- https://x.com/bunjavascript/status/1774842587431719184
- installable via PowerShell or npm https://x.com/bunjavascript/status/1774966012745814120

**Comment by mxschmitt** [comment]
Closing for now since we don't plan supporting bun in the near future.

**Pull request closed without merging**
