### PR TITLE
Add package manager choice for questions

### PR DESCRIPTION
**Pull request by vitalics**
add support pnpm package manager

### CODE REVIEW

**Comment by pavelfeldman** [comment]
How do you init using `pnpm`?  Are you running `pnpm init playwright@latest`? If so, can we detect the executable and derive the pnpm bit?

**Comment by vitalics** [comment]
the original issue was about choosing package manager to using in your project. Like an `npm` and `yarn` also has `pnpm` package manager. Also this manager has [init](https://github.com/pnpm/pnpm/issues/3505#issuecomment-1094131785) command like an npm.

**Comment by vitalics** [comment]
I agree with you. I review init packages such create react app and their is not using iint commands. Let's remove init commands in code at the next PR.

**Comment by vitalics** [comment]
I assume that we need to asking about package manager. Because initiating is using only once during the project (like crate-playwright or create-react) and in mostly cases user's doesn't know about other managers

**Comment by pavelfeldman** [comment]
What I am suggesting is that:
`yarn init playwright` creates a project that will use yarn, etc etc

**Comment by vitalics** [comment]
fully agree with you about who shall executing commands like `init`. But currently in repo you are execute commands like `npm/yarn install`, `npm/yarn playwright test`, etc
https://github.com/microsoft/create-playwright/blob/main/src/generator.ts#L175

and i made a change for supporting another package manager.

**Comment by pavelfeldman** [comment]
User executes init using preferred package manager. create-playwright detects which package manager was used and uses it to add packages / create helper commands.

**Comment by vitalics** [comment]
pnpm provides API like yarn or npm that's why I create a PR to support that package manager. `create-playwright` also detects which package manager was used and adds packages depending on `detectPackageManager` function, but if the package manager is pnpm - `create-playwright` will using npm(instead of pnpm in previous version)  and create `package.json` file(pnpm generates `pnpm.yaml` file)

Minimal repro for detect manager: 

package.json:
``` json
{
  "name": "my-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  }
}
```

index.js
``` js
console.log(process.env.npm_config_user_agent);
```

OUTPUT(my environment)
NPM:
`npm start` -> `npm/8.5.5 node/v16.15.0 darwin x64 workspaces/false`
YARN:
`yarn start` -> `yarn/1.22.15 npm/? node/v16.15.0 darwin x64`
PNPM:
`pnpm start` -> `pnpm/7.0.0 npm/? node/v14.17.0 darwin x64`

**Comment by vitalics** [comment]
Fixed comments that you mentioned

**Comment by mxschmitt** [comment]
Is this still something which you want to get merged? I'd recommend making the CI green.

**Comment by mxschmitt** [comment]
Superseded by https://github.com/microsoft/create-playwright/pull/36

**Pull request closed without merging**
